### PR TITLE
Updated c55 guide.

### PR DESCRIPTION
**Pull request by Blauker**
Updated c55 guide.

### CODE REVIEW

**Review by GorlikItsMe — APPROVED** [review]
For me looks good

**Comment by Blauker** [comment]
Also works fine on localhost

**Comment by GorlikItsMe** [comment]
ymm wait, there should not be `className` insteard `class` ?
@Maybe-afk

**Comment by Maybe-afk** [comment]
ye looks good u can merge @GorlikItsMe

**Pull request merged**
